<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
function wysiwyg_changes_wysiwyg_editor_settings_alter(&$settings, $context){
  if ($context['profile']->editor == 'ckeditor') {
    $settings['removeDialogTabs'] = 'link:upload;image:Upload';;
  }
}